In [56]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

#for KNN
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [57]:
df_merge = pd.read_csv('Merged0430.csv')
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823353 entries, 0 to 2823352
Data columns (total 27 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Accident_Index              object
 1   Accident_Severity           int64
 2   Accident_Severity3Category  object
 3   Accident_Severity2Category  object
 4   Number_of_Vehicles          int64
 5   Number_of_Casualties        int64
 6   Date                        object
 7   Month                       int64
 8   Year                        int64
 9   Day_of_Week                 object
 10  WeekdayEnd                  object
 11  Time                        object
 12  Hour                        float64
 13  Light_Conditions            int64
 14  Weather_Conditions          object
 15  Wind                        object
 16  Precipitation               object
 17  PrecipitationNumeric        int64
 18  RoadSurfaceCategorical      object
 19  RoadSurfaceNumeric          int64
 20  Road_Type                   object
 21  Speed_limit                 int64
 22  Urban_or_Rural_Area         object
 23  Vehicle_Reference           int64
 24  Vehicle_Type                float64
 25  Sex_of_Driver               object
 26  1st_Point_of_Impact         object
dtypes: float64(2), int64(10), object(15)
memory usage: 581.6+ MB

In [58]:
df_merge.shape

(2823353, 27)

In [59]:
#check null values
df_merge.isnull().sum()

Accident_Index                0
Accident_Severity             0
Accident_Severity3Category    0
Accident_Severity2Category    0
Number_of_Vehicles            0
Number_of_Casualties          0
Date                          0
Month                         0
Year                          0
Day_of_Week                   0
WeekdayEnd                    0
Time                          0
Hour                          0
Light_Conditions              0
Weather_Conditions            0
Wind                          0
Precipitation                 0
PrecipitationNumeric          0
RoadSurfaceCategorical        0
RoadSurfaceNumeric            0
Road_Type                     0
Speed_limit                   0
Urban_or_Rural_Area           0
Vehicle_Reference             0
Vehicle_Type                  0
Sex_of_Driver                 0
1st_Point_of_Impact           0
dtype: int64

In [60]:
pd.set_option('display.max_columns', None)
df_merge.head()

,Accident_Index,Accident_Severity,Accident_Severity3Category,Accident_Severity2Category,Number_of_Vehicles,Number_of_Casualties,Date,Month,Year,Day_of_Week,WeekdayEnd,Time,Hour,Light_Conditions,Weather_Conditions,Wind,Precipitation,PrecipitationNumeric,RoadSurfaceCategorical,RoadSurfaceNumeric,Road_Type,Speed_limit,Urban_or_Rural_Area,Vehicle_Reference,Vehicle_Type,Sex_of_Driver,1st_Point_of_Impact
0,200501BS00001,2,Serious,Serious,1,1,2005-01-04,1,2005,Tue,Weekday,17:42,17.0,1,Rain No Wind,Normal,Rain,3,Wet,2,TwoWayNonSeparated,30,Urban,1,2.0,Female,Front
1,200501BS00002,1,Slight,Slight,1,1,2005-01-05,1,2005,Wed,Weekday,17:36,17.0,2,Fine No Wind,Normal,Fine,1,Dry,1,TwoWaySeparated,30,Urban,1,3.0,Male,NearSide
2,200501BS00003,1,Slight,Slight,2,1,2005-01-06,1,2005,Thu,Weekday,00:15,0.0,2,Fine No Wind,Normal,Fine,1,Dry,1,TwoWayNonSeparated,30,Urban,1,3.0,Male,NearSide
3,200501BS00003,1,Slight,Slight,2,1,2005-01-06,1,2005,Thu,Weekday,00:15,0.0,2,Fine No Wind,Normal,Fine,1,Dry,1,TwoWayNonSeparated,30,Urban,2,2.0,Male,OffSide
4,200501BS00004,1,Slight,Slight,1,1,2005-01-07,1,2005,Fri,Weekday,10:35,10.0,1,Fine No Wind,Normal,Fine,1,Dry,1,TwoWayNonSeparated,30,Urban,1,2.0,Female,Front

In [61]:
df = df_merge.drop(columns = ['Accident_Index', 'Accident_Severity3Category', 'Accident_Severity2Category', 'Date', 'Month','Year', 'Day_of_Week', 'Time', 'Hour', 'Weather_Conditions', 'Precipitation',
                               'RoadSurfaceNumeric', 'Vehicle_Reference'], axis = 1)
df.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,WeekdayEnd,Light_Conditions,Wind,PrecipitationNumeric,RoadSurfaceCategorical,Road_Type,Speed_limit,Urban_or_Rural_Area,Vehicle_Type,Sex_of_Driver,1st_Point_of_Impact
0,2,1,1,Weekday,1,Normal,3,Wet,TwoWayNonSeparated,30,Urban,2.0,Female,Front
1,1,1,1,Weekday,2,Normal,1,Dry,TwoWaySeparated,30,Urban,3.0,Male,NearSide
2,1,2,1,Weekday,2,Normal,1,Dry,TwoWayNonSeparated,30,Urban,3.0,Male,NearSide
3,1,2,1,Weekday,2,Normal,1,Dry,TwoWayNonSeparated,30,Urban,2.0,Male,OffSide
4,1,1,1,Weekday,1,Normal,1,Dry,TwoWayNonSeparated,30,Urban,2.0,Female,Front

In [62]:
df_encoded = pd.get_dummies(df)
df_encoded = df_encoded.astype(int)
df_encoded.head()

,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Light_Conditions,PrecipitationNumeric,Speed_limit,Vehicle_Type,WeekdayEnd_Weekday,WeekdayEnd_Weekend,Wind_HighWind,Wind_Normal,RoadSurfaceCategorical_Dry,RoadSurfaceCategorical_Flood,RoadSurfaceCategorical_Frost,RoadSurfaceCategorical_Snow,RoadSurfaceCategorical_Wet,Road_Type_OneWay,Road_Type_Roundabout,Road_Type_SlipRoad,Road_Type_TwoWayNonSeparated,Road_Type_TwoWaySeparated,Urban_or_Rural_Area_Rural,Urban_or_Rural_Area_Urban,Sex_of_Driver_Female,Sex_of_Driver_Male,1st_Point_of_Impact_Back,1st_Point_of_Impact_Front,1st_Point_of_Impact_NearSide,1st_Point_of_Impact_NoImpact,1st_Point_of_Impact_OffSide
0,2,1,1,1,3,30,2,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,1,0,0,0
1,1,1,1,2,1,30,3,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0,0
2,1,2,1,2,1,30,3,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,1,0,0
3,1,2,1,2,1,30,2,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1
4,1,1,1,1,1,30,2,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0

In [63]:
df.shape

(2823353, 14)

In [64]:
df_encoded.shape

(2823353, 30)

In [74]:
#separate independent and dependent variables
X = df_encoded.drop('Accident_Severity', axis =1)
y = df_encoded['Accident_Severity']

In [76]:
#normalise independent variables
min_max_scaler = MinMaxScaler()
X_scaled = min_max_scaler.fit_transform(X)
X_scaled

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.5       , ..., 1.        , 0.        ,
        0.        ],
       [0.01515152, 0.        , 0.5       , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.03030303, 0.01086957, 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.01515152, 0.01086957, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.01515152, 0.01086957, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [78]:
#split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42)

In [80]:
X_train.shape

(2117514, 29)

In [82]:
X_test.shape

(705839, 29)

In [84]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [86]:
# Predict using the test set
y_pred = knn.predict(X_test)

In [88]:
# Print model accuracy score
accuracy_score_1 = accuracy_score(y_test, y_pred)
print(f"Accuracy ={round((accuracy_score_1 * 100), 4)}%")

Accuracy =84.8356%

### Train with different hyperparameters

In [90]:
knn = KNeighborsClassifier(n_neighbors=5, metric='manhattan')
knn.fit(X_train, y_train)

KNeighborsClassifier(metric='manhattan')

In [94]:
# Predict using the test set
# y_pred = knn.predict(X_test)
# Print model accuracy score
accuracy_score_1 = accuracy_score(y_test, y_pred)
print(f"Accuracy ={round((accuracy_score_1 * 100), 4)}%")

Accuracy =84.8344%

In [96]:
# Set up array of possible k values
possible_k = np.arange(50,500,100)
possible_k

array([ 50, 150, 250, 350, 450])

In [98]:
# Calculate accuracy for each k value
ac_scores=[]
for k in possible_k:
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)
    scores=round((accuracy_score(y_test, y_pred) * 100), 6)
    ac_scores.append(scores)
print ("Accuracy Scores :", ac_scores)

Accuracy Scores : [86.260181, 86.266415, 86.266415, 86.267832, 86.26769]